on:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          include-component-in-tag: true

      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.releases_created }}
      - uses: actions/setup-node@v4
        with:
          cache: "npm"
          node-version: 18
        if: ${{ steps.release.outputs.releases_created }}

      - run: npm ci
        if: ${{ steps.release.outputs.releases_created }}
      - run: |
          echo "$PACKAGES"
          echo "$PACKAGES" | jq -c '.[]' | npm publish -w
        env:
          PACKAGES: ${{toJSON(steps.release.outputs.paths_released)}}
        if: ${{ steps.release.outputs.releases_created }}
      # - uses: actions/checkout@v2
      #   if: ${{ steps.release.outputs.releases_created }}
      # - uses: actions/setup-node@v2
      #   with:
      #     cache: "npm"
      #     node-version: 18
      #     registry-url: "https://registry.npmjs.org"
      #   if: ${{ steps.release.outputs.releases_created }}
      # - run: npm ci
      #   if: ${{ steps.release.outputs.releases_created }}
      # - run: node ./scripts/publish.js '${{toJSON(steps.release.outputs)}}'
      #   env:
      #     NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}
      #   if: ${{ steps.release.outputs.releases_created }}
