on:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
      paths_released: ${{ steps.release.outputs.paths_released }}
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          include-component-in-tag: true
      - run: echo '${{toJSON(steps.release.outputs)}}'

  publish:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.releases_created == 'true' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: "npm"
          registry-url: "https://npm.pkg.github.com"
          node-version: 18

      - run: npm ci
      - run: |
          echo "$PACKAGES"
          echo "$PACKAGES" | jq -c -r 'fromjson | .[]' | \
          while read -r package; do
            echo "processing package $package"
            npm run build -w $package
            npm publish -w $package
          done
        env:
          PACKAGES: ${{ toJSON(needs.release-please.outputs.paths_released) }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
